language: java
jdk: oraclejdk8
sudo: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: mvn clean verify
notifications:
  slack:
    rooms:
      - modbiosys:cbXIhVIeXKhYc4ZaM9OO2KpY#sbtab
    on_success: never # default: always
    on_failure: always # default: always
  email:
    recipients:
      - granitguri.gg@gmail.com
      - zakharchuk.vn@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
