language: java
jdk: oraclejdk8
sudo: false
script: mvn clean verify
notifications:
  slack: modbiosys:cbXIhVIeXKhYc4ZaM9OO2KpY
    on_success: never # default: always
    on_failure: always # default: always
  email:
    recipients:
      - granitguri.gg@gmail.com
      - zakharchuk.vn@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
